import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface BudgetItem {
  category: string;
  amount: number;
  paid: number;
}

interface ChecklistItem {
  task: string;
  months: string;
  done: boolean;
}

const BRAND_COLOR: [number, number, number] = [90, 20, 40]; // wine
const GOLD_COLOR: [number, number, number] = [180, 140, 60];
const GRAY: [number, number, number] = [120, 120, 120];

function addHeader(doc: jsPDF, title: string) {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 40, "F");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(title, 20, 25);
  doc.setFontSize(9);
  doc.setTextColor(220, 200, 180);
  doc.text("Generated by Venue by Choice • venuebychoice.com", 20, 34);
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(
      `Page ${i} of ${pageCount} • ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
      105, 290, { align: "center" }
    );
  }
}

export function downloadBudgetPdf(items: BudgetItem[]) {
  const doc = new jsPDF();
  addHeader(doc, "Wedding Budget Planner");

  const totalBudget = items.reduce((s, i) => s + i.amount, 0);
  const totalPaid = items.reduce((s, i) => s + i.paid, 0);
  const remaining = totalBudget - totalPaid;

  // Summary
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Budget Summary", 20, 55);

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`Total Budget: ₹${totalBudget.toLocaleString("en-IN")}`, 20, 63);
  doc.text(`Total Paid: ₹${totalPaid.toLocaleString("en-IN")}`, 20, 70);
  doc.text(`Remaining: ₹${remaining.toLocaleString("en-IN")}`, 20, 77);

  // Progress bar
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(20, 81, 170, 4, 2, 2, "F");
  const paidWidth = totalBudget > 0 ? (totalPaid / totalBudget) * 170 : 0;
  doc.setFillColor(...GOLD_COLOR);
  doc.roundedRect(20, 81, paidWidth, 4, 2, 2, "F");

  // Table
  autoTable(doc, {
    startY: 95,
    head: [["Category", "Estimated (₹)", "Paid (₹)", "Remaining (₹)"]],
    body: items.map((i) => [
      i.category,
      i.amount.toLocaleString("en-IN"),
      i.paid.toLocaleString("en-IN"),
      (i.amount - i.paid).toLocaleString("en-IN"),
    ]),
    foot: [["Total", totalBudget.toLocaleString("en-IN"), totalPaid.toLocaleString("en-IN"), remaining.toLocaleString("en-IN")]],
    headStyles: { fillColor: BRAND_COLOR, fontSize: 9 },
    footStyles: { fillColor: [245, 240, 235], textColor: BRAND_COLOR, fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [252, 250, 248] },
    margin: { left: 20, right: 20 },
  });

  addFooter(doc);
  doc.save("wedding-budget-plan.pdf");
}

export function downloadChecklistPdf(items: ChecklistItem[]) {
  const doc = new jsPDF();
  addHeader(doc, "Wedding Checklist");

  const completed = items.filter((t) => t.done).length;
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Progress", 20, 55);

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`${completed} of ${items.length} tasks completed (${Math.round((completed / items.length) * 100)}%)`, 20, 63);

  // Progress bar
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(20, 67, 170, 4, 2, 2, "F");
  doc.setFillColor(...GOLD_COLOR);
  doc.roundedRect(20, 67, (completed / items.length) * 170, 4, 2, 2, "F");

  autoTable(doc, {
    startY: 80,
    head: [["Status", "Task", "Timeline"]],
    body: items.map((t) => [
      t.done ? "✓" : "○",
      t.task,
      `${t.months} months before`,
    ]),
    headStyles: { fillColor: BRAND_COLOR, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [252, 250, 248] },
    columnStyles: {
      0: { halign: "center", cellWidth: 18 },
      2: { cellWidth: 45 },
    },
    margin: { left: 20, right: 20 },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 0) {
        const done = items[data.row.index]?.done;
        data.cell.styles.textColor = done ? [40, 140, 70] : GRAY;
        data.cell.styles.fontStyle = done ? "bold" : "normal";
      }
    },
  });

  addFooter(doc);
  doc.save("wedding-checklist.pdf");
}

export function downloadGuestEstimatePdf(
  guestCount: number,
  mealType: string,
  cateringCost: number,
  venueCost: number,
  decorationCost: number,
  totalCost: number
) {
  const doc = new jsPDF();
  addHeader(doc, "Guest & Cost Estimate");

  doc.setFontSize(11);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Estimate Details", 20, 55);

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`Guest Count: ${guestCount}`, 20, 63);
  doc.text(`Meal Type: ${mealType.charAt(0).toUpperCase() + mealType.slice(1)}`, 20, 70);

  autoTable(doc, {
    startY: 82,
    head: [["Category", "Estimated Cost (₹)", "% of Total"]],
    body: [
      ["Catering", cateringCost.toLocaleString("en-IN"), `${Math.round((cateringCost / totalCost) * 100)}%`],
      ["Venue", venueCost.toLocaleString("en-IN"), `${Math.round((venueCost / totalCost) * 100)}%`],
      ["Decoration", decorationCost.toLocaleString("en-IN"), `${Math.round((decorationCost / totalCost) * 100)}%`],
    ],
    foot: [["Total", totalCost.toLocaleString("en-IN"), "100%"]],
    headStyles: { fillColor: BRAND_COLOR, fontSize: 9 },
    footStyles: { fillColor: [245, 240, 235], textColor: BRAND_COLOR, fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [252, 250, 248] },
    margin: { left: 20, right: 20 },
  });

  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("* Estimates are approximate and based on average market rates in Patna & Kolkata.", 20, (doc as any).lastAutoTable.finalY + 12);

  addFooter(doc);
  doc.save("guest-cost-estimate.pdf");
}
